In [9]:
import pandas as pd
df=pd.read_csv("D:\Projects\College Student Performance Analytics System\data/student_performance_1000.csv")

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\patuy\AppData\Local\Temp\ipykernel_10684\642465114.py:2: SyntaxWarning: invalid escape sequence '\P'
  df=pd.read_csv("D:\Projects\College Student Performance Analytics System\data/student_performance_1000.csv")

In [10]:
df.head()

,Student_ID,Gender,Study_Hours,Attendance,Internal_Marks,Assignment_Score,Previous_Grade,Final_Marks,Final_Result
0,1001,Male,3.4,94.0,62.0,60.0,B,39.0,Fail
1,1002,Female,5.3,97.0,51.0,71.0,B,38.0,Fail
2,1003,Male,4.1,78.0,78.0,80.0,D,43.0,Fail
3,1004,Male,2.3,69.0,81.0,72.0,C,38.0,Fail
4,1005,Male,1.9,84.0,37.0,51.0,C,35.0,Fail

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        1000 non-null   int64
 1   Gender            1000 non-null   object
 2   Study_Hours       1000 non-null   float64
 3   Attendance        1000 non-null   float64
 4   Internal_Marks    1000 non-null   float64
 5   Assignment_Score  1000 non-null   float64
 6   Previous_Grade    1000 non-null   object
 7   Final_Marks       1000 non-null   float64
 8   Final_Result      1000 non-null   object
dtypes: float64(5), int64(1), object(3)
memory usage: 70.4+ KB

In [4]:
df.describe()

,Student_ID,Study_Hours,Attendance,Internal_Marks,Assignment_Score,Final_Marks
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1500.500000,3.054000,78.295000,65.000000,69.398000,38.377000
std,288.819436,1.183835,11.452211,14.837525,12.089903,3.690324
min,1001.000000,0.500000,42.000000,30.000000,35.000000,35.000000
25%,1250.750000,2.275000,71.000000,54.000000,61.000000,35.000000
50%,1500.500000,3.000000,78.000000,65.000000,69.000000,37.000000
75%,1750.250000,3.800000,86.000000,75.000000,77.000000,41.000000
max,2000.000000,6.000000,100.000000,100.000000,100.000000,52.000000

In [5]:
df.isnull().sum()

Student_ID          0
Gender              0
Study_Hours         0
Attendance          0
Internal_Marks      0
Assignment_Score    0
Previous_Grade      0
Final_Marks         0
Final_Result        0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df['Gender']=df['Gender'].map({'Male':0,'Female':1})
df['Final_Result']=df['Final_Result'].map({'Fail':0,'Pass':1})

In [11]:
df["Total_Score"] = (
    df["Internal_Marks"] +
    df["Assignment_Score"] +
    df["Final_Marks"]
)
df["Study_Efficiency"] = df["Final_Marks"] / df["Study_Hours"]